language: node_js
node_js:
  - "lts/*"
before_install:
  - sudo apt-get install -y wine
install:
    - npm install
script:
    - npm run build-win
    - zip -r _builds/todoist-electron-win32-ia32 .
deploy:
  provider: releases
  api_key:
    secure: GIT_RELEASES_KEY
  file:
    - "todoist-electron-win32-ia32.zip"
  skip_cleanup: true
  on:
    tags: false
cache:
  apt: true
  directories:
    - node_modules