language: node_js
node_js:
  - 8
before_install:
  - sudo apt-get install -y wine
install:
    - npm install
script:
    - npm run build-win
    - zip -r windows.zip _builds/todoist-electron-win32-ia32
deploy:
  provider: releases
  api_key:
    secure: $GIT_RELEASES_KEY
  file:
    - "windows.zip"
  skip_cleanup: true
  on:
    tags: false
    branch: master
cache:
  apt: true
  directories:
    - node_modules