language: node_js
node_js:
  - 8
before_install:
  - sudo apt-get install -y wine
install:
    - npm install
script:
    - APP_VERSION=v0.1.$TRAVIS_BUILD_NUMBER
    - npm run build-win
    - zip -r Windows_$APP_VERSION.zip _builds/todoist-electron-win32-ia32
before_deploy:
    - git config --local user.name "Grand Silence"
    - git config --local user.email "mixtape774@gmail.com"
    - git tag "$APP_VERSION"
deploy:
  provider: releases
  api_key:
    secure: $GIT_RELEASES_KEY
  file:
    - "Windows_$APP_VERSION.zip"
  skip_cleanup: true
  branch: master
  on:
    tags: false
branches:
  only:
  - master
skip_commits:
  files:
    - .gitignore
    - jsconfig.json
    - launch.json
    - package.json
    - package-lock.json
    - README.md
    - rebuild_win.bat
cache:
  apt: true
  directories:
    - node_modules